# Generated by Django 5.0.1 on 2024-02-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_profile_user_profile_remove_customuser_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
