# Generated by Django 5.0.1 on 2024-02-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_complaint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complint_name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_anonymous',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
