# Generated by Django 5.0.1 on 2024-02-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
