# Generated by Django 5.0.1 on 2024-02-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_user', '0002_customcharityuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcharityuser',
            name='email',
        ),
    ]
