# Generated by Django 5.0.1 on 2024-02-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_user', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcharityuser',
            name='charity_country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
