# Generated by Django 5.0.1 on 2024-02-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_user', '0007_remove_customcharityuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_host',
            field=models.CharField(max_length=100),
        ),
    ]
